In [1]:
!pip install numpy

#### Exercise 1:
##### Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [8]:
import numpy as np

array = np.arange(1,11)

matrix = array.reshape(2,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Exercise 2:
##### Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [11]:
import numpy as np

array = np.arange(1,21)
extracted_elements = array[5:15]
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


#### Exercise 3
##### Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [14]:
import pandas as pd
data = {'apples':3,'banana':2,'oranges':1}

series = pd.Series(data)

series['pear'] = 4
print(series)

apples     3
banana     2
oranges    1
pear       4
dtype: int64


#### Exercise 4
##### Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [17]:
import pandas as pd
data = {'name':['Adam','Mariya','David','Arun','Anita','Henna','John','Laura','Helen','Eddie'],
        'age':[23,25,35,26,27,30,28,31,32,27],
        'gender':['Male','Female','Male','Male','Female','Female','Male','Female','Female','Male']}
df = pd.DataFrame(data)
print(df)

     name  age  gender
0    Adam   23    Male
1  Mariya   25  Female
2   David   35    Male
3    Arun   26    Male
4   Anita   27  Female
5   Henna   30  Female
6    John   28    Male
7   Laura   31  Female
8   Helen   32  Female
9   Eddie   27    Male


#### Exercise 5
##### Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [22]:
occupations = ['Programmer','Manager','Analyst','Manager','Analyst','Programmer','Analyst','Manager','Programmer','Analyst']
df['occupation'] = occupations

print(df)

     name  age  gender  occupation
0    Adam   23    Male  Programmer
1  Mariya   25  Female     Manager
2   David   35    Male     Analyst
3    Arun   26    Male     Manager
4   Anita   27  Female     Analyst
5   Henna   30  Female  Programmer
6    John   28    Male     Analyst
7   Laura   31  Female     Manager
8   Helen   32  Female  Programmer
9   Eddie   27    Male     Analyst


#### Exercise 6
##### Select the rows of the dataframe where the age is greater than or equal to 30.


In [27]:
filtered_df = df[df['age'] >=30]
print(filtered_df)

    name  age  gender  occupation
2  David   35    Male     Analyst
5  Henna   30  Female  Programmer
7  Laura   31  Female     Manager
8  Helen   32  Female  Programmer


#### Exercise 7
##### Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [25]:
import pandas as pd

df.to_csv('dataframe.csv',index=False)

new_df = pd.read_csv('dataframe.csv')
print(new_df)

     name  age  gender  occupation
0    Adam   23    Male  Programmer
1  Mariya   25  Female     Manager
2   David   35    Male     Analyst
3    Arun   26    Male     Manager
4   Anita   27  Female     Analyst
5   Henna   30  Female  Programmer
6    John   28    Male     Analyst
7   Laura   31  Female     Manager
8   Helen   32  Female  Programmer
9   Eddie   27    Male     Analyst
